### ISSUE TITLE
BUG LIST in 1.0.8 pre-release plugin(I am using 1.10.2 woominecraft and 1.10.2 paperspigot)

### ISSUE THREAD

**Issue by eric2788** [WooMinecraft/WooMinecraft#111]
btw let me explain that error happened in my server:
1. as image  https://gyazo.com/3df52c8a895f25fce747a3d7ef9dc1f4.gif
before /woo register
```
# Set this to the desired language file you wish to load.
#
# If your l10n is not available but one is that you know how to speak,consider
# contributing to this plugin at https://github.com/WooMinecraft/WooMinecraft/
lang: "en"

# This is how often, in seconds, the server will contact your WordPress installation
# to see if there are donations that need made.
update_interval: 1500

# You must set this to your WordPress site URL.  If you installed WordPress in a
# subdirectory, it should point there.
url: "http://playground.dev"

# This must match the WordPress key in your admin panel for WooMinecraft
# For security purposes, you MUST NOT leave this empty.
key: ""

# Set to true in order to toggle debug information
debug: false
```
after /woo register
```
> # Set this to the desired language file you wish to load.
key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```
i think i can add back option by myself:
```
# Set this to the desired language file you wish to load.
key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
lang: "en"
update_interval: 1500
url: "http://XXXXXXXl.net"
key: ""
debug: true
```
but error ?
`http://pastebin.com/9cgbTNCT`

the plugin version is 1.0.8 pre-release
i am using 1.10.2 woominecraft plugin for my server with paperspigot 1.10.2

and /woo check problem still existing, maybe you would fix it during this few days ?

2.  plugin keep generating a error and looping the product command:(duplicate and duplicate, not only execute once)
after i have bought the product in my wordpress
i ticked "complete payment" , and go to console and type /woo check

> [16:23:11] [Server thread/WARN]: [WooMinecraft] A JSONObject text must begin with '{' at 1 [character 2 line 1]
[16:23:11] [Server thread/WARN]: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
[16:23:11] [Server thread/WARN]: 	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
[16:23:11] [Server thread/WARN]: 	at org.json.JSONObject.<init>(JSONObject.java:195)
[16:23:11] [Server thread/WARN]: 	at org.json.JSONObject.<init>(JSONObject.java:319)
[16:23:11] [Server thread/WARN]: 	at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:142)
[16:23:11] [Server thread/WARN]: 	at com.plugish.woominecraft.Commands.WooCommand.onCommand(WooCommand.java:59)
[16:23:11] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[16:23:11] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[16:23:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:665)
[16:23:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:628)
[16:23:11] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:442)
[16:23:11] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:405)
[16:23:11] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:725)
[16:23:11] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:624)
[16:23:11] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

but nothing happen.......only this error for now......

before this exception , it was generated this error and auto executed all my history product command
(before i use 'say %s hi ' for my product command, but now i deleted the old command and reset , now is using 'say %s thank you' for my product command, but, he have executed both command,it means all history command i have used it also will be executed.)

**Comment by JayWood** [comment]
These issues will be fixed today, see changelog here - https://github.com/WooMinecraft/WooMinecraft/tree/dev-nightly#108

**Comment by eric2788** [comment]
@JayWood have this fixed version released? is it will turn to 1.0.9?

**Comment by JayWood** [comment]
A release has been issued, it's 1.0.8 ( non-PRE release version ) and is available here: https://www.spigotmc.org/resources/woominecraft.25517/

**Comment by JayWood** [comment]
@eric2788 please note, there is a corresponding WordPress release later today.

**Comment by eric2788** [comment]
good， i will try the latest version today.
i really love this plugin features,caz wordpress is freer than buycraft

**Comment by eric2788** [comment]
@JayWood  kidding me dude.......
https://gyazo.com/ed4d9cf627b3f2d73a64e3b7dcb93bc2
i cannot use /woo register how can i generate a key......

**Comment by Jogib** [comment]
@eric2788 
Read my last post in #109 
[https://github.com/WooMinecraft/WooMinecraft/issues/109#issuecomment-245044969]

And then follow the wiki for creating a product.

**Comment by JayWood** [comment]
@eric2788 `/woo register` was removed due to the problems it's caused, more bugs than benefits. If you're running a server, you should at the very least know how to edit a config. @Jogib provided a great how to.

I also have a wiki which covers what the config should look like by default.
https://github.com/WooMinecraft/WooMinecraft/wiki/Step-1:-Server-Plugin-Installation#plugin-config

Closing this thread as a duplicate.
