### ISSUE TITLE
java.lang.Exception

### ISSUE THREAD

**Issue by beeedee** [WooMinecraft/WooMinecraft#114]
Java = 8
Bukkit V. = 1.10.2-R0.1-SNAPSHOT
WooMinecraft V. = WooMinecraft v1.0.9-RC1-B1.10.2-R0.1

```
> Send command: woo register
> [02:20:01 INFO]: Usage: /woo check
> [02:26:16 WARN]: [WooMinecraft] Server Key is empty, this is insecure, check config.
> [02:26:16 WARN]: java.lang.Exception: Server Key is empty, this is insecure, check config.
> [02:26:16 WARN]: 	at com.plugish.woominecraft.WooMinecraft.validateConfig(WooMinecraft.java:103)
> [02:26:16 WARN]: 	at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:117)
> [02:26:16 WARN]: 	at com.plugish.woominecraft.Commands.WooCommand.onCommand(WooCommand.java:31)
> [02:26:16 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
> [02:26:16 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
> [02:26:16 WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:626)
> [02:26:16 WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchServerCommand(CraftServer.java:612)
> [02:26:16 WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.aL(DedicatedServer.java:398)
> [02:26:16 WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:362)
> [02:26:16 WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:643)
> [02:26:16 WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:547)
> [02:26:16 WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

### I do not generate a key

**Comment by Jogib** [comment]
@beeedee This is how to get it to work:
1. Install java plugin
2. start and stop server to generate config files.
3. In the config.yml, replace the domain name with your own. (must be complete path to your shop ex. http://mydomain.com/myshop/)
4. In the config.yml, add a random key with letters and numbers - Around 15 characters should do it
5. Install WP plugin
6. Go to the "Options -> Woo Minecraft"
7. Add the key you manually made in step 4, and save
8. create a product and buy it (Make a free one for starters)
9. Start your MC server and join it
10. Profit 😄 

@JayWood The wiki needs an update btw, also some text and guidelines for the java and WP plugin.

**Comment by spannerman79** [comment]
> This is how to get it to work:
> 1. Install java plugin
> 2. start and stop server to generate config files.
> 3. In the config.yml, replace the domain name with your own. (must be complete path to your shop ex. http://mydomain.com/myshop/)
> 4. In the config.yml, add a random key with letters and numbers - Around 15 characters should do it
> 5. Install WP plugin
> 6. Go to the "Options -> Woo Minecraft"
> 7. Add the key you manually made in step 4, and save
> 8. create a product and buy it (Make a free one for starters)
> 9. Start your MC server and join it
> 10. Profit

@Jogib the wiki outlines those steps already https://github.com/WooMinecraft/WooMinecraft/wiki - note the last edited date - **8 days** ago. Well before this issue was created

**Comment by JayWood** [comment]
@Jogib I'm always up for PR's if you have free time. You can submit PR's to the wiki not just code.

But as @spannerman79 said, this was updated a week or so ago on the wiki.

**Comment by Jogib** [comment]
@spannerman79 & @JayWood 
The wiki does actually outline that you need to use the command "/woo register" to autogenerate a key.

> ### Step 1: Server Plugin Installation
> **Explanation**
> - Lang: Set this to the desired language file you wish to load. See below the list of available languages.
> - **_Key: Randomly generated when you run /woo register. This is used in the WordPress installation. Don't give this key to anyone and don't change it by yourself! The Key will usually have 32 characters if not all the time :)_**
> - Url: A URL to your WordPress installation. If you installed WordPress in a subdirectory, it should point there.
> - Time_delay: The amount of seconds between web checks, 1500 is recommended.


Btw, I think it was me who updated the wiki 8 days ago, with the product you have to mark as downloadable, to actually automate the purchase.

I will update the wiki so everything is up to date, as soon as possible 😄

**Comment by beeedee** [comment]
```
[02:43:47 INFO]: BeeeDee issued server command: /woo check
[02:43:47 WARN]: [WooMinecraft] A JSONObject text must begin with '{' at 1 [character 2 line 1]
[02:43:47 WARN]: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
[02:43:47 WARN]: 	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
[02:43:47 WARN]: 	at org.json.JSONObject.<init>(JSONObject.java:195)
[02:43:47 WARN]: 	at org.json.JSONObject.<init>(JSONObject.java:319)
[02:43:47 WARN]: 	at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:142)
[02:43:47 WARN]: 	at com.plugish.woominecraft.Commands.WooCommand.onCommand(WooCommand.java:31)
[02:43:47 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[02:43:47 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
[02:43:47 WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:626)
[02:43:47 WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1299)
[02:43:47 WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1159)
[02:43:47 WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(SourceFile:37)
[02:43:47 WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(SourceFile:9)
[02:43:47 WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[02:43:47 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[02:43:47 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[02:43:47 WARN]: 	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[02:43:47 WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:688)
[02:43:47 WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:361)
[02:43:47 WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:643)
[02:43:47 WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:547)
[02:43:47 WARN]: 	at java.lang.Thread.run(Thread.java:745)
```
Bukkit V. = 1.10.2-R0.1-SNAPSHOT
WooMinecraft V. = WooMinecraft v1.0.9-RC1-B1.10.2-R0.1

### I see this error after making you say

**Comment by JayWood** [comment]
@beeedee set debugging to true in the config, re-run. If you have any sort of redirect occurring, OR if your url isn't pointing to your wordpress install this will happen.

**Comment by beeedee** [comment]
my website is becraft.gq

config url is 
http://becraft.gq/  (this is wordpress folder)
http://becraft.gq/shop/ (this is woocommerce link)
i don't understand ❓

**Comment by beeedee** [comment]
my new error is
```
**[01:15:48 INFO]: BeeeDee issued server command: /woo check
[01:15:48 WARN]: [WooMinecraft] Logging an improper server response
[01:15:48 ERROR]: [WooMinecraft] //**
[01:15:48 WARN]: [WooMinecraft] A JSONObject text must begin with '{' at 1 [character 2 line 1]
[01:15:48 WARN]: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
[01:15:48 WARN]: 	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
[01:15:48 WARN]: 	at org.json.JSONObject.
```

**Comment by spannerman79** [comment]
> [01:15:48 WARN]: [WooMinecraft] A JSONObject text must begin with '{' at 1 [character 2 line 1]

https://github.com/WooMinecraft/WooMinecraft/wiki#orgjsonjsonexception-a-jsonobject-text-must-begin-with--at-1-character-2-line-1

**Comment by beeedee** [comment]
I could not run plugin

1. error = [01:15:48 WARN]: [WooMinecraft] Logging an improper server response
2. error = [01:15:48 WARN]: [WooMinecraft] A JSONObject text must begin with '{' at 1 [character 2 line 1]

connect teamviewew and help me ?

**Comment by beeedee** [comment]
thank you all. I'm waiting for more stable operation of this plugin .

This time I'm gonna try the other systems. because I don't start and too many error 😢

**Comment by spannerman79** [comment]
> thank you all. I'm waiting for more stable operation of this plugin .

**Again** - re read the link i provided, being https://github.com/WooMinecraft/WooMinecraft/wiki#orgjsonjsonexception-a-jsonobject-text-must-begin-with--at-1-character-2-line-1

**Comment by beeedee** [comment]
Everything is correct and I still get the same error

> [01:15:48 INFO]: BeeeDee issued server command: /woo check
> [01:15:48 WARN]: [WooMinecraft] **Logging an improper server response**
> [01:15:48 ERROR]: [WooMinecraft] //
> [01:15:48 WARN]: [WooMinecraft] A JSONObject text must begin with '{' at 1 [character 2 line 1]
> [01:15:48 WARN]: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
> [01:15:48 WARN]: at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
> [01:15:48 WARN]: at org.json.JSONObject.

**Comment by JayWood** [comment]
@beeedee there's something interfering with the normal response on your server, I cannot say what it is, but I can say that you should not be getting just `//` as a response.

In issue #112 Falmon fixed it by setting his URL to the woo-commerce shop url, not sure why it worked as he didn't explain. 

I can also say that your site has a redirect, of some sort, which will cause the plugin not to work. Why your site is sending back just `//` I have no idea. When I first visit your site I'm immediately redirected to this URL: http://becraft.gq/?i=1 ( notice the `?i=1` ) but when I come back, it works just fine. This is not normal.

**Comment by JayWood** [comment]
Closing this, feel free to re-open should you have more to add. Considering my previous points this looks to be at the web server level.
