### ISSUE TITLE
Server Key is Empty, This is Insecure, check config.

### ISSUE THREAD

**Issue by landynlee** [WooMinecraft/WooMinecraft#121]
[WooMinecraft] Server Key is empty, this is insecure, check config.
[11:40:07 WARN]: java.lang.Exception: Server Key is empty, this is insecure, check config.
[11:40:07 WARN]:        at com.plugish.woominecraft.WooMinecraft.validateConfig(WooMinecraft.java:103)
[11:40:07 WARN]:        at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:117)
[11:40:07 WARN]:        at com.plugish.woominecraft.Commands.WooCommand.onCommand(WooCommand.java:31)
[11:40:07 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[11:40:07 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[11:40:07 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[11:40:07 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
[11:40:07 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412)
[11:40:07 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
[11:40:07 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[11:40:07 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[11:40:07 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by TekkitCommando** [comment]
Make a server key in your config.yml, it is no longer auto-generated.
