### ISSUE TITLE
JSONArray[0] not a string.

### ISSUE THREAD

**Issue by jhonwds** [WooMinecraft/WooMinecraft#143]
```[17:06:53] [Craft Scheduler Thread - 358/INFO]: [WooMinecraft] Sending Request
[17:06:53] [Craft Scheduler Thread - 358/INFO]: [WooMinecraft] URL Config Field: 
[17:06:53] [Craft Scheduler Thread - 358/INFO]: [WooMinecraft] Headers: [Date: Fri, 14 Apr 2017 21:05:57 GMT, Content-Type: application/json; charset=UTF-8, Transfer-Encoding: chunked, Connection: 
[17:06:53] [Craft Scheduler Thread - 358/INFO]: [WooMinecraft] HTTP Response Code: 200
[17:06:53] [Craft Scheduler Thread - 358/INFO]: [WooMinecraft] Content Body Snippet (128 chars): {"success":true,"data":{"A player":{"409":[false,false]}}}
[17:06:53] [Craft Scheduler Thread - 358/INFO]: [WooMinecraft] Player names acquired -- walking over them now.
[17:06:53] [Craft Scheduler Thread - 358/INFO]: [WooMinecraft] Checking for player: A player
[17:06:53] [Craft Scheduler Thread - 358/INFO]: [WooMinecraft] Walking over orders for player.
[17:06:53] [Craft Scheduler Thread - 358/INFO]: [WooMinecraft] Processing command for order: 409
[17:06:53] [Craft Scheduler Thread - 358/INFO]: [WooMinecraft] Command Set: [false,false]
[17:06:53] [Craft Scheduler Thread - 358/WARN]: [WooMinecraft] JSONArray[0] not a string.
[17:06:53] [Craft Scheduler Thread - 358/WARN]: org.json.JSONException: JSONArray[0] not a string.
[17:06:53] [Craft Scheduler Thread - 358/WARN]: at org.json.JSONArray.getString(JSONArray.java:403)
[17:06:53] [Craft Scheduler Thread - 358/WARN]: at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:207)
[17:06:53] [Craft Scheduler Thread - 358/WARN]: at com.plugish.woominecraft.Util.BukkitRunner.run(BukkitRunner.java:18)
[17:06:53] [Craft Scheduler Thread - 358/WARN]: at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
[17:06:53] [Craft Scheduler Thread - 358/WARN]: at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[17:06:53] [Craft Scheduler Thread - 358/WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[17:06:53] [Craft Scheduler Thread - 358/WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[17:06:53] [Craft Scheduler Thread - 358/WARN]: at java.lang.Thread.run(Thread.java:745)
```

What could be the cause of this? The connection to the website works just fine.
I hided site and player name for obvious reasons.
I have set my commands correctly but in the console it shows as false, false. Also Virtual And Downloadable is checked.

**Comment by spannerman79** [comment]
Set `debug: true` in your config and provide the log

**Comment by jhonwds** [comment]
Debug is on true. That's the full log.

**Comment by JayWood** [comment]
@jhonwds can you provide the command you've saved for that order id?

**Comment by jhonwds** [comment]
I have 2 commands set. First one:
msg %player% &3Thank you for your order. Here's your rank, enjoy!

pex user %player% group set elite

**Comment by JayWood** [comment]
I have a feeling the `&3` is the issue, but I'll test this today and let you know.

**Comment by JayWood** [comment]
Closing as resolved, cannot duplicate.
