### ISSUE TITLE
local hosting 

### ISSUE THREAD

**Issue by mrFloki** [WooMinecraft/WooMinecraft#156]
Hello poeple i have a problem i tried to run woo in localhost because am working on my mc server on my computer. i faced 2 problems  first i get this error in woo plugin mc:

[14:47:30 INFO]: Usage: /woo check
>woo check
[14:47:34 WARN]: [WooMinecraft] Illegal character in path at index 32: http://127.0.0.1/wordpress/shop/"
[14:47:34 WARN]: java.net.URISyntaxException: Illegal character in path at index 32: http://127.0.0.1/wordpress/shop/"
[14:47:34 WARN]:        at java.net.URI$Parser.fail(Unknown Source)
[14:47:34 WARN]:        at java.net.URI$Parser.checkChars(Unknown Source)
[14:47:34 WARN]:        at java.net.URI$Parser.parseHierarchical(Unknown Source)
[14:47:34 WARN]:        at java.net.URI$Parser.parse(Unknown Source)
[14:47:34 WARN]:        at java.net.URI.<init>(Unknown Source)
[14:47:34 WARN]:        at com.plugish.apache.http.client.utils.URIBuilder.<init>(URIBuilder.java:82)
[14:47:34 WARN]:        at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:120)
[14:47:34 WARN]:        at com.plugish.woominecraft.Commands.WooCommand.onCommand(WooCommand.java:28)
[14:47:34 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:47:34 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[14:47:34 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
[14:47:34 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(CraftServer.java:636)
[14:47:34 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java:437)
[14:47:34 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:400)
[14:47:34 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[14:47:34 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[14:47:34 WARN]:        at java.lang.Thread.run(Unknown Source)

and second problem when i add woo word press plugin and activate it i don't get any new menu in options panel. 
wordpress is hosted on local host same as mc.

**Comment by JayWood** [comment]
@mrFloki latest options is located under WooCommerce > Settings _(the bottom)_, it was moved, just haven't gotten around to updating the wiki yet.

As for the issue, if you read the first line, it tells you what is wrong:
> [14:47:34 WARN]: [WooMinecraft] Illegal character in path at index 32: http://127.0.0.1/wordpress/shop/"

Look at the quotes, looks like you have an extra one.
