### ISSUE TITLE
Executing Command

### ISSUE THREAD

**Issue by increedibad** [WooMinecraft/WooMinecraft#165]
My problem:
I've got connection with my site. After finishing some order in woo commerce error appears in console. Im running 1.11.2 Spiogt. I know, this plugin is for bukkit, but is there any way to  run in on my server?

 Saving...
[10:35:33 INFO]: [WooMinecraft] Sending Request
[10:35:33 INFO]: [WooMinecraft] URL Config Field: http://www.siedmiomorze.pl
[10:35:33 INFO]: [WooMinecraft] Headers: [Date: Mon, 31 Jul 2017 08:35:32 GMT, Server: WisePanel Web Server, Keep-Alive: timeout=15, max=300, Connection: Keep-Alive, Transfer-Encoding: chunked, Content-Type: application/json; charset=UTF-8]
[10:35:33 INFO]: [WooMinecraft] HTTP Response Code: 200
[10:35:33 INFO]: [WooMinecraft] Content Body Snippet (128 chars): ﻿{"success":true,"data":{"incredibad":{"44":["give incredibad arrow"],"43":["kill incredibad","kill incredibad"],"42":["give inc
[10:35:33 WARN]: [WooMinecraft] A JSONObject text must begin with '{' at 1 [character 2 line 1]
[10:35:33 WARN]: org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
[10:35:33 WARN]:at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
[10:35:33 WARN]:at org.json.JSONObject.<init>(JSONObject.java:195)
[10:35:33 WARN]:at org.json.JSONObject.<init>(JSONObject.java:319)
[10:35:33 WARN]:at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:137)
[10:35:33 WARN]:at com.plugish.woominecraft.Util.BukkitRunner.run(BukkitRunner.java:18)
[10:35:33 WARN]:at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[10:35:33 WARN]:at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[10:35:33 WARN]:at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:35:33 WARN]:at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[10:35:33 WARN]:at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[10:35:33 WARN]:at java.lang.Thread.run(Thread.java:745)

### Server Information:
* **Host:*enderchest.pl*
* **URL:*siedmiomorze.pl*
* **WordPress URL:*www.siedmiomorze.pl*

### Config.yml
https://www.dropbox.com/s/xa3g8bjapc4x9p3/config.yml?dl=0

**Comment by spannerman79** [comment]
> Config.yml
> 
> https://www.dropbox.com/s/xa3g8bjapc4x9p3/config.yml?dl=0

I don't look at dropbox - use Gist or hastebin etc

**Comment by increedibad** [comment]
https://hastebin.com/serecovara.bash

**Comment by JayWood** [comment]
@increedibad Looks like your www. prefix redirects to the non www. site as evident in google chrome.
![cd375a7d23b0999a5cb32e3ce3a25382](https://user-images.githubusercontent.com/2303074/29003866-bbd73650-7a8c-11e7-9dc7-5b6c02f9717c.png)

Change your url to the non-www version of the site, this is usually a tale-tale sign of a redirect or just bad request:

> [10:35:33 WARN]: [WooMinecraft] A JSONObject text must begin with '{' at 1 [character 2 line 1]

**Comment by increedibad** [comment]
OK. I've got it!

All you have to do is add line in your wp-config.php file:

define('WP_HOME','http://www.example.com');
define('WP_SITEURL','http://www.example.com');

The problem was also in my .htaccess file, caused by Wordpress plugin WP Total Cache

Really thanks for help man!

**Comment by JayWood** [comment]
@increedibad Those look awfully like the urls you'd setup normally during install. Which get saved to Settings > General under the WordPress Address and Site Address fields.

Either way glad you got it fixed!
