### ISSUE TITLE
Getting errors on console and also not working for me, adding error on console

### ISSUE THREAD

**Issue by evilspiritYT** [WooMinecraft/WooMinecraft#243]
[18:49:15 INFO]: evilspirit issued server command: /woo check
[18:49:15 WARN]: [WooMinecraft] Server returned HTTP response code: 403 for URL: https://logesport.in//wp-json/wmc/v1/server/9j8FMktU7NxhJraYeIPSM0PiOhKLYXhFxA030onFyAI4o6zBtZX0uNl2uuRbzCzd
[18:49:15 WARN]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://logesport.in//wp-json/wmc/v1/server/9j8FMktU7NxhJraYeIPSM0PiOhKLYXhFxA030onFyAI4o6zBtZX0uNl2uuRbzCzd
[18:49:15 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
[18:49:15 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
[18:49:15 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
[18:49:15 WARN]:        at java.net.URL.openStream(URL.java:1068)
[18:49:15 WARN]:        at com.plugish.woominecraft.WooMinecraft.getPendingOrders(WooMinecraft.java:253)
[18:49:15 WARN]:        at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:133)
[18:49:15 WARN]:        at com.plugish.woominecraft.WooCommand.onCommand(WooCommand.java:27)
[18:49:15 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:49:15 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[18:49:15 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761)
[18:49:15 WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1869)
[18:49:15 WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1677)
[18:49:15 WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[18:49:15 WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[18:49:15 WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[18:49:15 WARN]:        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[18:49:15 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[18:49:15 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[18:49:15 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[18:49:15 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106)
[18:49:15 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1099)
[18:49:15 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[18:49:15 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1060)
[18:49:15 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:975)
[18:49:15 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by JayWood** [comment]
HTTP 403 is "Forbidden"
- If you're using Cloudflare, you need to whitelist your Minecraft server's IP ( google it )
- Speak to your host otherwise.

If hit the endpoint it works - so it's likely an issue with Minecraft > Web Server communications.

**Comment by evilspiritYT** [comment]
Thank you its working now

**Comment by barenn7** [comment]
anyone found how to fix this issue ?
It seems to block my website on blank page and minecraft server is shutting off

**Comment by JayWood** [comment]
@barenn7 please open a separate ticket, this is unrelated.
