### ISSUE TITLE
Error with GSON parsing

### ISSUE THREAD

**Issue by mkko120** [WooMinecraft/WooMinecraft#245]
Hi, 
I'm trying to set up your plugin on my server.
I've tried to run the Minecraft server and I'm and getting a weird error in the console after writing command `/woo check`:

```
[18:24:27] [Server thread/WARN]: [WooMinecraft] java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
[18:24:27] [Server thread/WARN]: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
[18:24:27] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
[18:24:27] [Server thread/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:887)
[18:24:27] [Server thread/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:852)
[18:24:27] [Server thread/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:801)
[18:24:27] [Server thread/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:773)
[18:24:27] [Server thread/WARN]: 	at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:142)
[18:24:27] [Server thread/WARN]: 	at com.plugish.woominecraft.WooCommand.onCommand(WooCommand.java:27)
[18:24:27] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[18:24:27] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[18:24:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810)
[18:24:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:772)
[18:24:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:453)
[18:24:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:420)
[18:24:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1388)
[18:24:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120)
[18:24:27] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290)
[18:24:27] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:829)
[18:24:27] [Server thread/WARN]: Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
[18:24:27] [Server thread/WARN]: 	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
[18:24:27] [Server thread/WARN]: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
[18:24:27] [Server thread/WARN]: 	... 16 more
```
While when manually entering the site URL (https://example.com/wp-json/wmc/v1/server/secretcode) the response in the browser is:

```
{"orders":[]}
```

### System info:
**System:** Ubuntu 20.04
**Web:** Wordpress 5.7.1 on nginx/1.18.0 (Ubuntu), plugin version 1.4
**Minecraft:** git-Tuinity-"b12d0cc" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
**Cloudflare:** yes, with IP whitelisted

Kindest regards,
mkko120

EDIT 1:
I have the webserver on the same machine as the Minecraft server so I also tried entering the URL as `https://localhost:80` and it also failed so it's not a Cloudflare-generated issue.

**Comment by mkko120** [comment]
I've edited some code so now I'm not getting an error but now I have this:
```
[19:19:17 INFO]: [WooMinecraft] {"orders":[{"player":"LemonKotekPL","order_id":2041,"commands":["lp user LemonKotekPL parent addtemp svip 30d"]}]}
[19:19:17 INFO]: [WooMinecraft]  No purchases available - please try again soon.
```
still working on getting it working

**Comment by mkko120** [comment]
ok i think now i broke something XD
```
[06:46:39 WARN]: Unexpected exception while parsing console command "woo check"
org.bukkit.command.CommandException: Unhandled exception executing command 'woo' in plugin WooMinecraft v1.3.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Tuinity-"b12d0cc"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Tuinity-"b12d0cc"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Tuinity-"b12d0cc"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:772) ~[patched_1.16.5.jar:git-Tuinity-"b12d0cc"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:453) ~[patched_1.16.5.jar:git-Tuinity-"b12d0cc"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.16.5.jar:git-Tuinity-"b12d0cc"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1388) ~[patched_1.16.5.jar:git-Tuinity-"b12d0cc"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Tuinity-"b12d0cc"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Tuinity-"b12d0cc"]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NoClassDefFoundError: okhttp3/OkHttpClient
        at com.plugish.woominecraft.WooMinecraft.sendProcessedOrders(WooMinecraft.java:226) ~[?:?]
        at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:209) ~[?:?]
        at com.plugish.woominecraft.WooCommand.onCommand(WooCommand.java:31) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Tuinity-"b12d0cc"]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: okhttp3.OkHttpClient
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:182) ~[patched_1.16.5.jar:git-Tuinity-"b12d0cc"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Tuinity-"b12d0cc"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at com.plugish.woominecraft.WooMinecraft.sendProcessedOrders(WooMinecraft.java:226) ~[?:?]
        at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:209) ~[?:?]
        at com.plugish.woominecraft.WooCommand.onCommand(WooCommand.java:31) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Tuinity-"b12d0cc"]
        ... 9 more
```

**Comment by mkko120** [comment]
If the problem exist in your plugin you can use my forks of woominecraft and woominecraft-wp:
https://github.com/mkko120-studio/WooMinecraft-nopremium/
https://github.com/mkko120-studio/woominecraft-wp-nonpremium/
I wont make a pull request because I've already modified it to allow nonpremium accounts.
