### ISSUE TITLE
Error: Expected BEGIN_OBJECT but was STRING

### ISSUE THREAD

**Issue by ArnoPi** [WooMinecraft/WooMinecraft#251]
[14:21:18 WARN]: [WooMinecraft] java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
[14:21:18 WARN]: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
[14:21:18 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
[14:21:18 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:887)
[14:21:18 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:852)
[14:21:18 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:801)
[14:21:18 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:773)
[14:21:18 WARN]:        at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:142)
[14:21:18 WARN]:        at com.plugish.woominecraft.WooCommand.onCommand(WooCommand.java:27)
[14:21:18 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:21:18 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[14:21:18 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:809)
[14:21:18 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:771)
[14:21:18 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
[14:21:18 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378)
[14:21:18 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209)
[14:21:18 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997)
[14:21:18 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
[14:21:18 WARN]:        at java.lang.Thread.run(Thread.java:748)
[14:21:18 WARN]: Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
[14:21:18 WARN]:        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
[14:21:18 WARN]:        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
[14:21:18 WARN]:        ... 16 more

**Comment by SNokerYT** [comment]
i also have this problem https://paste.md-5.net/togegigofe.md

**Comment by JayWood** [comment]
This is due to many factors, mostly related to hosts blocking WordPress API endpoints or poorly implemented anti-bot tactics. See the FAQ here - https://github.com/WooMinecraft/WooMinecraft/wiki#orgjsonjsonexception-a-jsonobject-text-must-begin-with--at-1-character-2-line-1
