### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AloxosUY** [WooMinecraft/WooMinecraft#264]
Hello, I currently use 1.18.1 and WooMinecraft is a plugin that attracted me, I put it on my server that uses Java 17, but it comes out in red when I launch the / p command

Any recommendation?

I also wanted to know if there was a discord to join me :)

**Comment by AloxosUY** [comment]
Unexpected exception while parsing console command "woo"
org.bukkit.command.CommandException: Cannot execute command 'woo' in plugin WooMinecraft v1.4.1-1.18 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3385-Spigot-78a14d9-c93fcba]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchServerCommand(CraftServer.java:806) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3385-Spigot-78a14d9-c93fcba]
        at net.minecraft.server.dedicated.DedicatedServer.bf(DedicatedServer.java:453) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3385-Spigot-78a14d9-c93fcba]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:429) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3385-Spigot-78a14d9-c93fcba]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1206) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3385-Spigot-78a14d9-c93fcba]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1034) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3385-Spigot-78a14d9-c93fcba]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3385-Spigot-78a14d9-c93fcba]
        at java.lang.Thread.run(Thread.java:833) [?:?]



This is the error that I get

**Comment by jerzean** [comment]
> Hello, I currently use 1.18.1 and WooMinecraft is a plugin that attracted me, I put it on my server that uses Java 17, but it comes out in red when I launch the / p command
> 
> Any recommendation?
> 
> I also wanted to know if there was a discord to join me :)
`WooMinecraft v1.4.1-1.18 - plugin is disabled`
Also said discord link [Discord](https://discord.gg/3XBPyq8)

**Comment by JayWood** [comment]
Spigot.yml must have bungee set to true if the server.properties online-mode is false. Fully offline/cracked servers is not supported.
