### ISSUE TITLE
Server returned HTTP

### ISSUE THREAD

**Issue by EsmitJonz** [WooMinecraft/WooMinecraft#285]
Hello, what is the cause of this error? 
Server returned HTTP response code: 403 for URL:Server returned HTTP response code: 403 for URL: https://lotuscraft.ir/store/******

**Comment by EsmitJonz** [comment]
[05:13:19 INFO]: [WooMinecraft] Checking connection to server
[05:13:19 INFO]: [WooMinecraft]  Status: Bad, 403 Forbidden
[05:13:19 INFO]: [WooMinecraft] Checking Rest Api Url
[05:13:19 INFO]: [WooMinecraft] Checking base URL: https://lotuscraft.ir/store/
[05:13:19 INFO]: [WooMinecraft]  Status: Bad, 403 Forbidden
[05:13:21 INFO]: [WooMinecraft] Checking base URL: https://lotuscraft.ir/store/
[05:13:21 INFO]: [WooMinecraft] Server returned HTTP response code: 403 for URL: https://lotuscraft.ir/store/******
[05:13:21 INFO]: [WooMinecraft] Logging website reply

**Comment by JayWood** [comment]
403 forbidden means you are not allowed to access `/wp-json/wmc/v1` on that server. 

Looks like your REST feed is disabled.

![image](https://user-images.githubusercontent.com/2303074/192106286-fbd0d5a5-c8b9-4e9b-b75c-ed5d897b4ace.png)

Talk to your host.

**Comment by EsmitJonz** [comment]
> 403 forbidden به این معنی است که شما مجاز به دسترسی `/wp-json/wmc/v1`به آن سرور نیستید.
> 
> به نظر می رسد فید REST شما غیرفعال است.
> 
> ![تصویر](https://user-images.githubusercontent.com/2303074/192106286-fbd0d5a5-c8b9-4e9b-b75c-ed5d897b4ace.png)
> 
> با میزبان خود صحبت کنید.

ow do I activate it?

**Comment by JayWood** [comment]
the rest endpoint is active if the plugin is active, but given your site will not allow access to the base URL of `/wp-json` that implies that your host is completely blocking your rest endpoints altogether - or, you have wordpress installed elsewhere.

**Comment by EsmitJonz** [comment]
Is this URL correct?
https://lotuscraft.ir/store/index.php?rest_route=/wp/v2/product/

**Comment by EsmitJonz** [comment]
I activated REST feed, check again now

**Comment by JayWood** [comment]
set `prettyPermalinks` to `false` in your configt and set rest base to `/index.php?rest_route=/wmc/v1/server`

**Comment by EsmitJonz** [comment]
[17:07:06 INFO]: [WooMinecraft] Checking base URL: https://lotuscraft.ir/store/index.php?rest_route=/wmc/v1/server/
[17:07:07 INFO]: [WooMinecraft] Server returned HTTP response code: 403 for URL: https://lotuscraft.ir/store/index.php?rest_route=/wmc/v1/server/******
[17:07:07 INFO]: [WooMinecraft] Logging website reply
...
[17:07:07 WARN]: [WooMinecraft] Pending orders is empty completely
[17:07:07 INFO]: [WooMinecraft]  No purchases available - please try again soon.

**Comment by EsmitJonz** [comment]
[config.yml.txt](https://github.com/WooMinecraft/WooMinecraft/files/9641333/config.yml.txt)

**Comment by JayWood** [comment]
If you're using Cloudflare you'll want to whitelist/allow that url/path if you're not already. Otherwise I'd suggest speaking with your host on the issue. There's nothing more I can do here unfortunately 😢

**Comment by EsmitJonz** [comment]
What is the reason why the plugin does not support offline servers?

**Comment by EsmitJonz** [comment]
And don't you want to add support for offline servers to the plugin?

**Comment by JayWood** [comment]
Offline/cracked servers are illegal - I paid for the software and will not help others who stole it. Offline servers are supported via bungeecord, but the main server ( lobby ) must be online in order to authenticate the players.

**Comment by EsmitJonz** [comment]
Hello, what is the cause of this error?

[15:46:39 WARN]: [WooMinecraft] Plugin WooMinecraft v1.4.5-1.18 generated an exception while executing task 28
java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because the return value of "java.lang.Exception.getMessage()" is null
        at com.plugish.woominecraft.WooCommand.lambda$checkSubcommand$0(WooCommand.java:102) ~[WooMinecraft-1.4.5-1.18rc.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-379]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-379]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-379]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by JayWood** [comment]
A command you have stored in a product is an empty string or null.
