### ISSUE TITLE
Not sending the request to the website

### ISSUE THREAD

**Issue by EsmitJonz** [WooMinecraft/WooMinecraft#289]
Hi

What is the cause of this error?

And why, after the delivery of the purchased item, no request is sent to the website to remove the purchase that has been delivered.

[20:50:10 INFO]: OGHDEHEII issued server command: /woo check
[20:50:20 WARN]: [WooMinecraft] Plugin WooMinecraft v1.4.5-1.18 generated an exception while executing task 12
java.lang.NoClassDefFoundError: okhttp3/OkHttpClient
        at com.plugish.woominecraft.WooMinecraft.sendProcessedOrders(WooMinecraft.java:249) ~[WooMinecraft-1.4.5-1.18.jar:?]
        at com.plugish.woominecraft.WooMinecraft.check(WooMinecraft.java:232) ~[WooMinecraft-1.4.5-1.18.jar:?]
        at com.plugish.woominecraft.WooCommand.lambda$checkSubcommand$0(WooCommand.java:94) ~[WooMinecraft-1.4.5-1.18.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-379]        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-379]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-379]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassNotFoundException: okhttp3.OkHttpClient
        ... 9 more
[20:50:21 INFO]: Gave 6 ۵۵;۲۵۵;۲۵۵m[Apple] to OGHDEHEII

**Comment by EsmitJonz** [comment]
Error: okhttp3/OkHttpClient
Please help me

**Comment by jerzean** [comment]
its due to using paperspigot, the methods used in the plugin are stripped out of paperspigot

**Comment by EsmitJonz** [comment]
> its due to using paperspigot, the methods used in the plugin are stripped out of paperspigot

Hello . Now I'm a little confused
I tested both on paper and on the spigot and still had the same problem
If you have a solution, please tell me
